import { test } from "node:test";
import assert from "node:assert/strict";
import { genericPlugin } from "../../src/plugins/generic.ts";
import { buildTree, fixture, makeCtx, writeFiles } from "./helpers.ts";

const lines = (n: number, text = "x") => Array.from({ length: n }, () => text).join("\n") + "\n";

test("own values count non-blank lines, files, the largest file and TODO lines per directory", async () => {
  const root = fixture({
    "README.md": "# title\n\nbody\n",
    "src/a.rs": "fn a() {}\n\n// TODO: x\n// FIXME y\n",
    "src/b.rs": lines(7),
    "src/deep/c.rs": "c\n",
  });
  const values = await genericPlugin.collect(makeCtx(buildTree(root)));
  assert.deepEqual(values[""], { loc: 2, files: 1, max_file_loc: 2, todo_density: 0 });
  assert.deepEqual(values["src"], { loc: 10, files: 2, max_file_loc: 7, todo_density: 2 });
  assert.deepEqual(values["src/deep"], { loc: 1, files: 1, max_file_loc: 1, todo_density: 0 });
});

test("binary, lock, minified, vendored and generated files are skipped", async () => {
  const root = fixture({
    "keep.ts": "a\n",
    "image.png": Buffer.from([0x89, 0x50, 0x00, 0x01, 0x0a]),
    "Cargo.lock": lines(500),
    "app.min.js": lines(50),
    "gen.rs": "// @generated by protoc\n" + lines(300),
    "vendor/lib.c": lines(80),
  });
  const values = await genericPlugin.collect(makeCtx(buildTree(root)));
  assert.deepEqual(values[""], { loc: 1, files: 1, max_file_loc: 1, todo_density: 0 });
  assert.equal(values["vendor"], undefined);
});

test("large files yield findings scaled by size whose effect brings max_file_loc down to the threshold", async () => {
  const root = fixture({
    "big/huge.rs": lines(4200),
    "big/large.rs": lines(2100),
    "small/one.rs": lines(1200),
    "small/two.rs": lines(10),
  });
  const findings = (await genericPlugin.findings!(makeCtx(buildTree(root)))).filter((f) => f.source === "large-file");
  const byFile = Object.fromEntries(findings.map((f) => [f.file, f]));
  assert.deepEqual(Object.keys(byFile).sort(), ["big/huge.rs", "big/large.rs", "small/one.rs"]);
  assert.equal(byFile["big/huge.rs"].severity, "high");
  assert.equal(byFile["big/large.rs"].severity, "medium");
  assert.equal(byFile["small/one.rs"].severity, "low");
  assert.deepEqual(byFile["big/huge.rs"].metricEffects, { max_file_loc: 2100 - 4200 });
  assert.deepEqual(byFile["big/large.rs"].metricEffects, {});
  assert.deepEqual(byFile["small/one.rs"].metricEffects, { max_file_loc: 1000 - 1200 });
  assert.equal(byFile["small/one.rs"].node, "small");
});

test("TODO clusters of three or more lines yield one finding per file, with ids stable across edits", async () => {
  const root = fixture({
    "a.ts": "// TODO one\n// FIXME two\n// HACK three\n",
    "b.ts": "// TODO one\n// TODO two\n",
  });
  const tree = buildTree(root);
  const todo = async () => (await genericPlugin.findings!(makeCtx(tree))).filter((f) => f.source === "todo");
  const before = await todo();
  assert.equal(before.length, 1);
  assert.equal(before[0].file, "a.ts");
  assert.deepEqual(before[0].metricEffects, { todo_density: -3 });

  writeFiles(root, { "a.ts": "import x\n\n// TODO one\n// FIXME two\n// HACK three\n// XXX four\n" });
  const after = await todo();
  assert.equal(after[0].id, before[0].id);
  assert.deepEqual(after[0].metricEffects, { todo_density: -4 });
});
